{ config, pkgs, inputs, lib, ... }: {
  users.users.radioaddition.packages = with pkgs; [
    adwsteamgtk
    atuin
    bat
    bat-extras.batman
    bottles
    boxbuddy
    btop
    cartridges
    collision
    curl
    direnv
    discover-overlay
    distrobox
    docker-compose
    eza
    feather
    firefox
    fragments
    freshfetch
    gcc
    gettext
    git
    git-repo
    github-desktop
    glas
    gleam
    glib
    gnome.dconf-editor
    gnome-extension-manager
    gnome.gnome-boxes
    gnome.gnome-tweaks
    gnome.polari
    gnome.seahorse
    gnumake
    goofcord
    gparted
    guake
    helvum
    home-manager
    hyfetch
    impression
    iosevka
    jamesdsp
    keepassxc
    librewolf
    llama-cpp
    lutris
    meslo-lgs-nf
    mindustry-wayland
    monophony
    mpv
    neovim
    neovim-gtk
    nix-search-cli
    nodePackages_latest.pnpm
    nodejs-slim
    onionshare-gui
    openrazer-daemon
    pavucontrol
    perl
    picard
    pika-backup
    pinentry-gnome3
    pipx
    pnpm-shell-completion
    polychromatic
    protonmail-bridge
    protonmail-bridge-gui
    protonplus
    protonvpn-gui
    ptyxis
    python3
    redis
    ripgrep
    sassc
    shattered-pixel-dungeon
    simplex-chat-desktop
    topgrade
    tor-browser
    tuckr
    usbtop
    ventoy-full
    wget
    wl-clipboard
    wlrctl
    xmrig-mo
    zoxide
  ];
}
